# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20161107_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.FileField(default=1, upload_to=''),
        ),
    ]
