# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20161107_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
