# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20161109_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='is_favorite',
        ),
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
